version: '3.5'

services:
  api:
    container_name: api
    build: 
      context: .
    command: bash -c "go get . && go run ."
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: on-failure
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=schedule
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - app_network
  
  db:
    container_name: db
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=schedule
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network: